@extends('School_Dashboard.Admin_Layouts.app')

@section('title', 'Teacher ID Card Generation History')

@section('content')
    <div class="container my-4">
        <div class="card shadow-sm border-0 rounded-4">
            <div class="card-header bg-primary">
                <h3 class="card-title mb-0 text-white fw-bold">
                    <i class="fa-solid fa-chalkboard-teacher"></i> Teacher ID Card Generation History
                </h3>
            </div>

            <div class="card-body">
                <!-- ✅ DataTable -->
                <div class="table-responsive">
                    <table id="historyTable" class="table table-bordered table-striped table-hover align-middle">
                        <thead class="table-dark">
                            <tr>
                                <th width="5%">#</th>
                                <th width="25%">Teacher Info</th>
                                <th width="12%">Generation Type</th>
                                <th width="12%">Action Type</th>
                                <th width="15%">Generated By</th>
                                <th width="8%">Total</th>
                                <th width="15%">Last Generated</th>
                                <th width="8%">Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- ✅ Modal: View All Teachers List -->
    <div class="modal fade" id="allTeachersModal" tabindex="-1" data-bs-keyboard="false" data-bs-backdrop="static" aria-labelledby="scrollableModalLabel" >

        <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header bg-info text-white">
                    <h3 class="modal-title">
                        <i class="fa fa-users"></i> All Teachers in This Generation
                    </h3>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info">
                        <i class="fa fa-info-circle"></i> Total Teachers: <strong id="totalTeachersCount">0</strong>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover align-middle">
                            <thead class="table-dark">
                                <tr>
                                    <th width="10%">#</th>
                                    <th width="40%">Teacher ID</th>
                                    <th width="50%">Teacher Name</th>
                                </tr>
                            </thead>
                            <tbody id="allTeachersTableBody"></tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- ✅ Modal: Teacher Complete History -->
    <div class="modal fade" id="teacherHistoryModal" tabindex="-1" data-bs-keyboard="false" data-bs-backdrop="static" aria-labelledby="scrollableModalLabel" >

        <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header bg-primary text-white">
                    <h3 class="modal-title">
                        <i class="fa fa-history"></i> Complete Generation History
                    </h3>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <!-- Teacher Info Card -->
                    <div id="teacherInfo" class="mb-4"></div>

                    <!-- Summary Stats -->
                    <div class="row mt-4 mb-4">
                        <div class="col-md-4">
                            <div class="card bg-light border">
                                <div class="card-body text-center">
                                    <h6 class="text-muted fs-5 fw-bold">Preview Count</h6>
                                    <h3 id="previewCount" class="text-primary fw-bold">0</h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-light border">
                                <div class="card-body text-center">
                                    <h6 class="text-muted fs-5 fw-bold">Generate Count</h6>
                                    <h3 id="generateCount" class="text-success fw-bold">0</h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-light border">
                                <div class="card-body text-center">
                                    <h6 class="text-muted fs-5 fw-bold">Total Count</h6>
                                    <h3 id="totalCount" class="text-warning fw-bold">0</h3>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- History Table -->
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover align-middle">
                            <thead class="table-dark">
                                <tr>
                                    <th width="5%">#</th>
                                    <th width="25%">Date & Time</th>
                                    <th width="20%">Generation Type</th>
                                    <th width="20%">Action Type</th>
                                    <th width="30%">Generated By</th>
                                </tr>
                            </thead>
                            <tbody id="historyDetailsBody"></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            // ✅ DataTable Initialization
            var table = $('#historyTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('teachers.idCardHistoryData') }}",
                    type: 'GET',
                    error: function(xhr) {
                        alert('Error loading data: ' + xhr.status);
                    }
                },
                columns: [
                    { data: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'teacher_info' },
                    { data: 'generation_type' },
                    { data: 'action_type' },
                    { data: 'generated_by' },
                    { data: 'total_count', orderable: false },
                    { data: 'last_generated' },
                    { data: 'actions', orderable: false, searchable: false }
                ],
                order: [[6, 'desc']], // Sort by last_generated
                pageLength: 25,
                language: {
                    processing: '<i class="fa fa-spinner fa-spin fa-3x text-primary"></i><br>Loading...'
                }
            });

            // ✅ View All Teachers Modal
            $('#historyTable').on('click', '.view-all-teachers', function() {
                const ids = $(this).data('ids').toString().split(',');
                const names = $(this).data('names').toString().split(',');
                
                const uniqueTeachers = [];
                const seen = new Set();
                
                ids.forEach((id, index) => {
                    const cleanId = id.trim();
                    if (!seen.has(cleanId)) {
                        seen.add(cleanId);
                        uniqueTeachers.push({
                            id: cleanId,
                            name: names[index] ? names[index].trim() : 'N/A'
                        });
                    }
                });

                $('#totalTeachersCount').text(uniqueTeachers.length);
                
                const tbody = $('#allTeachersTableBody').empty();
                uniqueTeachers.forEach((teacher, i) => {
                    tbody.append(`
                        <tr>
                            <td class="text-center">${i + 1}</td>
                            <td><span class="badge bg-primary">${teacher.id}</span></td>
                            <td><strong>${teacher.name}</strong></td>
                        </tr>
                    `);
                });

                $('#allTeachersModal').modal('show');
            });

            // ✅ View Teacher History Modal
            $('#historyTable').on('click', '.view-teacher-history', function() {
                var teacherId = $(this).data('id');
                var type = $(this).data('type');

                $.ajax({
                    url: `/admin/teachers/id-card-history/details/${teacherId}`,
                    method: 'GET',
                    success: function(data) {
                        const history = data.history;
                        const totalGenerations = data.total_generations;

                        if (history.length > 0) {
                            const first = history[0];
                            const previewCount = history.filter(d => d.action_type === 'preview').length;
                            const generateCount = history.filter(d => d.action_type === 'generate').length;

                            // ✅ Teacher Info Display
                            if (type === 'all') {
                                $('#teacherInfo').html(`
                                    <div class="card bg-light border-0">
                                        <div class="card-body text-center">
                                            <h4 class="text-primary">
                                                <i class="fa fa-users"></i> All Teachers ID Card Generation History
                                            </h4>
                                            <p class="text-muted">Showing collective generation history for all teachers batch</p>
                                        </div>
                                    </div>
                                `);
                            } else {
                                $('#teacherInfo').html(`
                                    <div class="card bg-light border-0">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p class="mb-2">
                                                        <strong><i class="fa fa-id-badge text-primary"></i> Teacher ID:</strong> 
                                                        <span class="badge bg-primary fs-6">${first.teacher_id}</span>
                                                    </p>
                                                    <p class="mb-2">
                                                        <strong><i class="fa fa-user text-success"></i> Name:</strong> 
                                                        <span class="text-dark">${first.teacher_name}</span>
                                                    </p>
                                                </div>
                                                <div class="col-md-6">
                                                    <p class="mb-2">
                                                        <strong><i class="fa fa-phone text-info"></i> Mobile:</strong> 
                                                        <span class="text-dark">${first.mobile || 'N/A'}</span>
                                                    </p>
                                                    <p class="mb-2">
                                                        <strong><i class="fa fa-envelope text-warning"></i> Email:</strong> 
                                                        <span class="text-dark">${first.email || 'N/A'}</span>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                `);
                            }

                            // ✅ History Details Table
                            const tbody = $('#historyDetailsBody').empty();
                            history.forEach((item, i) => {
                                const date = new Date(item.generated_at).toLocaleString('en-IN', {
                                    day: '2-digit',
                                    month: 'short',
                                    year: 'numeric',
                                    hour: '2-digit',
                                    minute: '2-digit',
                                    hour12: true
                                });

                                const genBadge = item.generation_type === 'single' ? 'bg-danger' : 'bg-info';
                                const actBadge = item.action_type === 'preview' ? 'bg-success' : 'bg-warning text-dark';

                                tbody.append(`
                                    <tr>
                                        <td class="text-center">${i + 1}</td>
                                        <td><i class="fa fa-calendar text-muted"></i> ${date}</td>
                                        <td><span class="badge ${genBadge}">${item.generation_type.toUpperCase()}</span></td>
                                        <td><span class="badge ${actBadge}">${item.action_type.toUpperCase()}</span></td>
                                        <td><i class="fa fa-user-circle text-secondary"></i> ${item.generated_by}</td>
                                    </tr>
                                `);
                            });

                            // ✅ Update Stats
                            $('#previewCount').text(previewCount);
                            $('#generateCount').text(generateCount);
                            $('#totalCount').text(totalGenerations);
                        } else {
                            $('#teacherInfo').html('<div class="alert alert-warning">No history found</div>');
                            $('#historyDetailsBody').html('<tr><td colspan="5" class="text-center text-muted">No records available</td></tr>');
                            $('#previewCount, #generateCount, #totalCount').text('0');
                        }

                        $('#teacherHistoryModal').modal('show');
                    },
                    error: function(xhr) {
                        alert('Error loading history details: ' + xhr.status);
                    }
                });
            });
        });
    </script>
@endpush

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
    <style>
        /* Table Styling */
        #historyTable {
            border-radius: 0.6rem;
            overflow: hidden;
        }

        #historyTable thead {
            background-color: #000000;
            color: #fff;
            text-align: center;
        }

        .table-hover tbody tr:hover {
            background-color: #e3f2fd;
        }

        /* Modal Styling */
        .modal-content {
            border-radius: 1rem;
            border: none;
            box-shadow: 0 5px 20px rgba(0, 0, 0, 0.2);
        }

        .modal-body {
            background-color: #f9fafc;
        }

        /* Cards inside Modal */
        .card.bg-light {
            border: none;
            border-radius: 0.75rem;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);
        }

        /* Badges */
        .badge {
            font-size: 0.85rem;
            font-weight: 500;
            letter-spacing: 0.3px;
            padding: 0.4em 0.8em;
        }

        /* View All Teachers Button */
        .btn.view-all-teachers {
            white-space: nowrap;
            font-weight: 600;
        }

        .btn.view-all-teachers:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(0, 123, 255, 0.3);
            transition: all 0.2s;
        }

        /* Loading Spinner */
        .dataTables_processing {
            background: rgba(255, 255, 255, 0.95);
            border-radius: 0.5rem;
            padding: 2rem;
        }

        /* Responsive */
        @media (max-width: 768px) {
            .modal-lg {
                max-width: 95% !important;
            }

            .table-responsive {
                font-size: 0.85rem;
            }

            .badge {
                font-size: 0.75rem;
            }
        }
    </style>
@endpush